_wandb:
    value:
        cli_version: 0.21.0
        e:
            ugy5osjc0csaq3zsh6r0w7kafel2hokf:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                codePath: DemandForecastService/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "138889400320"
                email: oduguwadamilola40@gmail.com
                executable: /Users/onyekachiobute/Documents/RestaurantAIServices/DemandForecastService/.venv/bin/python3
                git:
                    commit: 9ff6d2f490e553e6c786da71849a381376689947
                    remote: https://github.com/damilojohn/RestaurantAIServices.git
                host: Damilolas-Macbook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.0-arm64-arm-64bit-Mach-O
                program: /Users/onyekachiobute/Documents/RestaurantAIServices/DemandForecastService/main.py
                python: CPython 3.13.5
                root: /Users/onyekachiobute/Documents/RestaurantAIServices/DemandForecastService
                startedAt: "2025-07-22T12:18:02.205309Z"
                writerId: ugy5osjc0csaq3zsh6r0w7kafel2hokf
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 13
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
