_wandb:
    value:
        cli_version: 0.21.0
        e:
            tos98t0xqxkjcbqnadysrd4sg1g7idn5:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: DemandForecastService/main.py
                codePathLocal: DemandForecastService/main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "149416960000"
                executable: /Users/onyekachiobute/Documents/RestaurantAIServices/DemandForecastService/.venv/bin/python3.13
                git:
                    commit: ef8af92c2ed7d751f5ab9f1b16722390b66c1f4e
                    remote: https://github.com/damilojohn/RestaurantAIServices.git
                host: Damilolas-Macbook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.0-arm64-arm-64bit-Mach-O
                program: /Users/onyekachiobute/Documents/RestaurantAIServices/DemandForecastService/main.py
                python: CPython 3.13.5
                root: /Users/onyekachiobute/Documents/RestaurantAIServices
                startedAt: "2025-07-26T08:54:18.149266Z"
                writerId: tos98t0xqxkjcbqnadysrd4sg1g7idn5
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 13
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
